// Category-level fallback images (used by OnboardingUI, ScanScreen, etc.)
export const foodAssets = {
  bowl: require('./recipes/teriyaki-chicken-bowl.png'),
  breakfast: require('./recipes/avocado-toast-poached-egg.png'),
  burger: require('./recipes/smash-cheeseburger.png'),
  dessert: require('./recipes/chocolate-mug-cake.png'),
  pasta: require('./recipes/creamy-tomato-rigatoni.png'),
  salad: require('./recipes/crunchy-chickpea-salad.png'),
};

// Per-recipe images for RecommendationsScreen and recipe cards.
// Placeholder PNGs are bundled at build time; run scripts/download-food-images.sh
// then restart Expo with `expo start -c` to swap in real Pexels photos.
// eslint-disable-next-line @typescript-eslint/no-require-imports
export const recipeAssets: Record<string, number> = {
  'avocado-toast-poached-egg': require('./recipes/avocado-toast-poached-egg.png'),
  'beef-broccoli-stir-fry': require('./recipes/beef-broccoli-stir-fry.png'),
  'beef-pho': require('./recipes/beef-pho.png'),
  'belgian-waffles-berries': require('./recipes/belgian-waffles-berries.png'),
  'berry-banana-smoothie': require('./recipes/berry-banana-smoothie.png'),
  'bibimbap': require('./recipes/bibimbap.png'),
  'breakfast-burrito': require('./recipes/breakfast-burrito.png'),
  'bulgogi-beef': require('./recipes/bulgogi-beef.png'),
  'butter-chicken': require('./recipes/butter-chicken.png'),
  'caprese-sandwich': require('./recipes/caprese-sandwich.png'),
  'carne-asada-tacos': require('./recipes/carne-asada-tacos.png'),
  'chicken-biryani': require('./recipes/chicken-biryani.png'),
  'chicken-piccata': require('./recipes/chicken-piccata.png'),
  'chicken-shawarma': require('./recipes/chicken-shawarma.png'),
  'chicken-souvlaki': require('./recipes/chicken-souvlaki.png'),
  'chiles-rellenos': require('./recipes/chiles-rellenos.png'),
  'chocolate-mug-cake': require('./recipes/chocolate-mug-cake.png'),
  'cinnamon-banana-oats': require('./recipes/cinnamon-banana-oats.png'),
  'creamy-tomato-rigatoni': require('./recipes/creamy-tomato-rigatoni.png'),
  'crispy-fish-tacos': require('./recipes/crispy-fish-tacos.png'),
  'crispy-tofu-power-bowl': require('./recipes/crispy-tofu-power-bowl.png'),
  'crunchy-chickpea-salad': require('./recipes/crunchy-chickpea-salad.png'),
  'eggplant-parmesan': require('./recipes/eggplant-parmesan.png'),
  'falafel-wrap': require('./recipes/falafel-wrap.png'),
  'fettuccine-alfredo': require('./recipes/fettuccine-alfredo.png'),
  'french-toast': require('./recipes/french-toast.png'),
  'garlic-butter-spaghetti': require('./recipes/garlic-butter-spaghetti.png'),
  'garlic-chicken-rice-bowl': require('./recipes/garlic-chicken-rice-bowl.png'),
  'granola-yogurt-bowl': require('./recipes/granola-yogurt-bowl.png'),
  'greek-salad': require('./recipes/greek-salad.png'),
  'greek-yogurt-parfait': require('./recipes/greek-yogurt-parfait.png'),
  'gyudon': require('./recipes/gyudon.png'),
  'huevos-rancheros': require('./recipes/huevos-rancheros.png'),
  'lamb-tagine': require('./recipes/lamb-tagine.png'),
  'loaded-grilled-cheese': require('./recipes/loaded-grilled-cheese.png'),
  'mango-sticky-rice': require('./recipes/mango-sticky-rice.png'),
  'mapo-tofu': require('./recipes/mapo-tofu.png'),
  'margherita-flatbread-pizza': require('./recipes/margherita-flatbread-pizza.png'),
  'mezze-platter': require('./recipes/mezze-platter.png'),
  'miso-glazed-salmon': require('./recipes/miso-glazed-salmon.png'),
  'mushroom-risotto': require('./recipes/mushroom-risotto.png'),
  'orzo-pasta-salad': require('./recipes/orzo-pasta-salad.png'),
  'pad-see-ew': require('./recipes/pad-see-ew.png'),
  'pad-thai-shrimp': require('./recipes/pad-thai-shrimp.png'),
  'pan-seared-salmon-dill': require('./recipes/pan-seared-salmon-dill.png'),
  'panang-curry-beef': require('./recipes/panang-curry-beef.png'),
  'poke-bowl': require('./recipes/poke-bowl.png'),
  'pulled-pork-sandwich': require('./recipes/pulled-pork-sandwich.png'),
  'red-curry-shrimp': require('./recipes/red-curry-shrimp.png'),
  'scrambled-eggs-toast': require('./recipes/scrambled-eggs-toast.png'),
  'seafood-paella': require('./recipes/seafood-paella.png'),
  'shakshuka': require('./recipes/shakshuka.png'),
  'sheet-pan-lemon-chicken': require('./recipes/sheet-pan-lemon-chicken.png'),
  'smash-cheeseburger': require('./recipes/smash-cheeseburger.png'),
  'smoked-salmon-bagel': require('./recipes/smoked-salmon-bagel.png'),
  'spaghetti-carbonara': require('./recipes/spaghetti-carbonara.png'),
  'spinach-feta-omelet': require('./recipes/spinach-feta-omelet.png'),
  'spring-rolls-peanut': require('./recipes/spring-rolls-peanut.png'),
  'tandoori-chicken': require('./recipes/tandoori-chicken.png'),
  'teriyaki-chicken-bowl': require('./recipes/teriyaki-chicken-bowl.png'),
  'thai-basil-chicken': require('./recipes/thai-basil-chicken.png'),
  'thai-green-curry-chicken': require('./recipes/thai-green-curry-chicken.png'),
  'tonkotsu-ramen': require('./recipes/tonkotsu-ramen.png'),
  'turkey-avocado-sandwich': require('./recipes/turkey-avocado-sandwich.png'),
  'vegetable-lo-mein': require('./recipes/vegetable-lo-mein.png'),
};
