import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { NavArrowLeft, NavArrowRight } from 'iconoir-react-native';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import type { MainTabParamList } from '../navigation/types';
import { onboardingV3Persistence } from '../onboarding-v3/state/onboardingV3Persistence';
import { primaryGoalLabels, type PersonalizedOnboardingProfile } from '../onboarding-v3/state/personalizedOnboarding';
import { foodPreferencesPersistence } from '../state/foodPreferences';
import { useOkyoStore } from '../state/useOkyoStore';
import { colors, fontFamilies, radius, spacing } from '../theme/okyoTheme';

type Navigation = NativeStackNavigationProp<MainTabParamList>;

export function ProfileScreen() {
  const navigation = useNavigation<Navigation>();
  const refreshPrimaryGoal = useOkyoStore((state) => state.refreshPrimaryGoal);
  const completedMeals = useOkyoStore((state) => state.completedMeals);
  const [profile, setProfile] = useState<PersonalizedOnboardingProfile | null>(null);
  const [dietaryCount, setDietaryCount] = useState(0);
  const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([onboardingV3Persistence.readPersonalizedProfile(), foodPreferencesPersistence.read()]).then(([stored, dietary]) => { setProfile(stored); setDietaryCount(dietary.allergies.length + dietary.restrictions.length + dietary.avoidances.length + dietary.dislikes.length); }); }, []);
  const goBack = () => { if (navigation.canGoBack()) navigation.goBack(); };
  const save = async () => { if (!profile) return; setSaving(true); try { await onboardingV3Persistence.writePersonalizedProfile(profile); await refreshPrimaryGoal(); Alert.alert('Profile saved'); } catch { Alert.alert('Couldn’t save profile', 'Try again.'); } finally { setSaving(false); } };
  const totalSavings = completedMeals.reduce((sum, meal) => sum + Math.max(0, meal.estimatedSavings ?? 0), 0);
  const totalProtein = completedMeals.reduce((sum, meal) => sum + (meal.proteinGrams ?? 0), 0);
  const totalCarbs = completedMeals.reduce((sum, meal) => sum + (meal.carbohydratesGrams ?? 0), 0);
  const totalFat = completedMeals.reduce((sum, meal) => sum + (meal.fatGrams ?? 0), 0);
  if (!profile) return <View accessibilityRole="progressbar" style={styles.loading}><ActivityIndicator color={colors.coral} /></View>;
  return <SafeAreaView style={styles.safeArea}><View style={styles.header}><Pressable accessibilityLabel="Go back" accessibilityRole="button" onPress={goBack} style={styles.back}><NavArrowLeft color={colors.ink} height={25} width={25} /></Pressable><Text style={styles.headerTitle}>Profile</Text></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.hero}><View style={styles.avatar}><Image accessibilityLabel="Profile avatar" resizeMode="contain" source={require('../../assets/profile-avatar-bob.png')} style={styles.avatarImage} /></View><Text style={styles.heroTitle}>{profile.name || 'Your Okyo profile'}</Text><Text style={styles.heroMeta}>{profile.primaryGoal ? primaryGoalLabels[profile.primaryGoal] : 'Choose what Okyo should optimize for'}</Text></View><Text style={styles.label}>NAME</Text><TextInput accessibilityLabel="Name" maxLength={30} onChangeText={(name) => setProfile({ ...profile, name })} placeholder="Your name" placeholderTextColor={colors.muted} style={styles.input} value={profile.name} /><Text style={styles.label}>PRIMARY GOAL</Text><View accessibilityLabel={`Primary goal: ${profile.primaryGoal ? primaryGoalLabels[profile.primaryGoal] : 'Not set'}`} style={styles.goalReadOnly}><Text style={styles.goalText}>{profile.primaryGoal ? primaryGoalLabels[profile.primaryGoal] : 'Not set'}</Text><Text style={styles.goalHint}>Set during onboarding</Text></View><Text style={styles.label}>YOUR OKYO TOTALS</Text><View style={styles.statsGrid}><Stat label="Estimated saved" value={`$${totalSavings.toFixed(0)}`} /><Stat label="Protein" value={`${Math.round(totalProtein)}g`} /><Stat label="Carbs" value={`${Math.round(totalCarbs)}g`} /><Stat label="Fat" value={`${Math.round(totalFat)}g`} /></View><Text style={styles.label}>FOOD PREFERENCES</Text><Pressable accessibilityRole="button" onPress={() => navigation.navigate('DietaryPreferencesScreen')} style={styles.row}><View><Text style={styles.rowTitle}>Dietary preferences</Text><Text style={styles.rowBody}>{dietaryCount ? `${dietaryCount} saved preferences` : 'None set'}</Text></View><NavArrowRight color={colors.muted} height={19} width={19} /></Pressable><Pressable accessibilityRole="button" disabled={saving} onPress={() => void save()} style={styles.save}>{saving ? <ActivityIndicator color={colors.surface} /> : <Text style={styles.saveText}>Save profile</Text>}</Pressable></ScrollView></SafeAreaView>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: colors.background, flex: 1 }, loading: { alignItems: 'center', backgroundColor: colors.background, flex: 1, justifyContent: 'center' }, header: { alignItems: 'center', flexDirection: 'row', gap: 8, paddingHorizontal: spacing.gutter, paddingVertical: 10 }, back: { alignItems: 'center', height: 44, justifyContent: 'center', marginLeft: -10, width: 44 }, headerTitle: { color: colors.ink, fontFamily: fontFamilies.extraBold, fontSize: 22 }, content: { paddingBottom: 150, paddingHorizontal: spacing.gutter }, hero: { alignItems: 'center', paddingVertical: 18 }, avatar: { alignItems: 'center', backgroundColor: colors.coralSoft, borderRadius: 42, height: 84, justifyContent: 'center', overflow: 'hidden', width: 84 }, avatarImage: { height: 84, width: 84 }, heroTitle: { color: colors.ink, fontFamily: fontFamilies.extraBold, fontSize: 24, marginTop: 10 }, heroMeta: { color: colors.body, fontFamily: fontFamilies.body, fontSize: 14, marginTop: 3 }, label: { color: colors.muted, fontFamily: fontFamilies.bold, fontSize: 11.5, letterSpacing: 0.8, marginBottom: 8, marginLeft: 4, marginTop: 24 }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.panel, borderWidth: 1, color: colors.ink, fontFamily: fontFamilies.body, fontSize: 16, minHeight: 52, paddingHorizontal: 15 }, goalReadOnly: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.panel, borderWidth: 1, minHeight: 64, justifyContent: 'center', paddingHorizontal: 15 }, goalHint: { color: colors.muted, fontFamily: fontFamilies.body, fontSize: 12, marginTop: 3 }, statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, stat: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, flexBasis: '47%', flexGrow: 1, minHeight: 74, justifyContent: 'center', paddingHorizontal: 14 }, statValue: { color: colors.ink, fontFamily: fontFamilies.extraBold, fontSize: 22 }, statLabel: { color: colors.body, fontFamily: fontFamilies.body, fontSize: 12, marginTop: 3 }, goalText: { color: colors.body, fontFamily: fontFamilies.bold, fontSize: 14 }, row: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.panel, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 64, padding: 15 }, rowTitle: { color: colors.ink, fontFamily: fontFamilies.bold, fontSize: 15 }, rowBody: { color: colors.body, fontFamily: fontFamilies.body, fontSize: 12.5, marginTop: 3 }, save: { alignItems: 'center', backgroundColor: colors.ink, borderRadius: radius.button, justifyContent: 'center', marginTop: 28, minHeight: 52 }, saveText: { color: colors.surface, fontFamily: fontFamilies.extraBold, fontSize: 16 } });
