import type {
  Badge,
  GroceryList,
  LeaderboardEntry,
  Recipe,
  RestaurantPack,
  ScanResult,
  ShareCard,
  XpEventDefinition,
} from './types.js';

export const mockScanResults: ScanResult[] = [
  {
    id: '001',
    dishName: 'Spicy Vodka Rigatoni',
    bestGuessDishName: 'Spicy Vodka Rigatoni',
    bestGuessNote: 'Clear demo food scan.',
    scanState: 'clear_food',
    restaurantStyle: 'Italian-American',
    restaurantPrice: 38,
    homemadeCost: 6.4,
    estimatedSavings: 31.6,
    confidence: 0.94,
    matchScore: 8.4,
    difficulty: 'Easy',
    modes: ['Restaurant Copy', 'Budget', 'Healthy'],
    recipeId: 'recipe-spicy-vodka-rigatoni',
    groceryListId: 'grocery-spicy-vodka-rigatoni',
    shareCardId: 'share-spicy-vodka-rigatoni',
  },
  {
    id: '002',
    dishName: 'Cheddar-style Biscuits',
    bestGuessDishName: 'Cheddar-style Biscuits',
    bestGuessNote: 'Clear demo food scan.',
    scanState: 'clear_food',
    restaurantStyle: 'Seafood chain inspired',
    restaurantPrice: 12,
    homemadeCost: 2.5,
    estimatedSavings: 9.5,
    confidence: 0.88,
    matchScore: 9.1,
    difficulty: 'Easy',
    modes: ['Restaurant Copy', 'Budget', 'Healthy'],
    recipeId: 'recipe-cheddar-biscuits',
    groceryListId: 'grocery-cheddar-biscuits',
    shareCardId: 'share-cheddar-biscuits',
  },
  {
    id: '003',
    dishName: 'Cava-style Grain Bowl',
    bestGuessDishName: 'Cava-style Grain Bowl',
    bestGuessNote: 'Clear demo food scan.',
    scanState: 'clear_food',
    restaurantStyle: 'Mediterranean',
    restaurantPrice: 17,
    homemadeCost: 5.8,
    estimatedSavings: 11.2,
    confidence: 0.81,
    matchScore: 8.2,
    difficulty: 'Easy',
    modes: ['Restaurant Copy', 'Budget', 'Healthy'],
    recipeId: 'recipe-cava-grain-bowl',
    groceryListId: 'grocery-cava-grain-bowl',
    shareCardId: 'share-cava-grain-bowl',
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: 'recipe-spicy-vodka-rigatoni-restaurant-copy',
    scanResultId: '001',
    title: 'Spicy Vodka Rigatoni Inspired-by',
    mode: 'Restaurant Copy',
    description: 'A creamy tomato rigatoni with parmesan, gentle heat, and a glossy restaurant-style sauce.',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    totalTimeMinutes: 30,
    activeTimeMinutes: 20,
    servings: 2,
    skillLevel: 'Easy',
    difficulty: 'Easy',
    estimatedHomemadeCost: 6.4,
    estimatedSavings: 31.6,
    mainIngredientsSummary: 'rigatoni, tomato paste, cream, parmesan, red pepper flakes',
    equipment: ['large pot', 'skillet', 'tongs or spoon', 'measuring cup'],
    bestFor: 'a cozy restaurant-style pasta night',
    ingredients: [
      { name: 'rigatoni', quantity: '8 oz' },
      { name: 'tomato paste', quantity: '3 tbsp' },
      { name: 'heavy cream', quantity: '1/2 cup' },
      { name: 'parmesan', quantity: '1/3 cup grated' },
      { name: 'red pepper flakes', quantity: '1 tsp', pantryItem: true },
      { name: 'olive oil', quantity: '2 tbsp', pantryItem: true },
    ],
    ingredientGroups: [
      {
        component: 'Noodles',
        items: [{ name: 'rigatoni', quantity: '8 oz' }],
      },
      {
        component: 'Sauce',
        items: [
          { name: 'tomato paste', quantity: '3 tbsp' },
          { name: 'heavy cream', quantity: '1/2 cup' },
          { name: 'parmesan', quantity: '1/3 cup grated' },
        ],
      },
      {
        component: 'Finishing',
        items: [
          { name: 'red pepper flakes', quantity: '1 tsp', pantryItem: true },
          { name: 'olive oil', quantity: '2 tbsp', pantryItem: true },
        ],
      },
    ],
    steps: [
      'Bring a pot of salted water to a boil, then cook rigatoni 1 minute less than the package says so it stays bouncy in the sauce.',
      'Reserve 1 cup pasta water before draining; the starchy water helps the sauce cling instead of turning soupy.',
      'Warm olive oil in a skillet over medium heat for 1 minute, then stir in tomato paste and red pepper flakes until brick red and fragrant.',
      'Lower the heat and stir in heavy cream for 1 minute until the sauce looks smooth and orange.',
      'Add rigatoni and parmesan, tossing for 1-2 minutes with splashes of pasta water until glossy.',
      'Taste, then add small pinches of salt, black pepper, or extra red pepper flakes until it tastes bright.',
    ],
    substitutions: [
      'Use penne or mezzi rigatoni if rigatoni is unavailable.',
      'Swap parmesan for pecorino for a sharper finish.',
    ],
    avoidMistake: 'Do not drain all the pasta water; it is the easiest way to fix a thick sauce.',
    mistakeWarning: 'Do not drain all the pasta water; it is the easiest way to fix a thick sauce.',
    storageAndReheating: 'Store up to 3 days. Reheat with a splash of water or milk to loosen the sauce.',
    storage: 'Store up to 3 days. Reheat with a splash of water or milk to loosen the sauce.',
    pantryNote: 'Assumes olive oil, salt, pepper, and red pepper flakes are already in the pantry.',
    confidenceNote: 'Mock recipe based on the visible dish style; ingredients and costs are estimates.',
    spicePairings: ['basil', 'black pepper', 'extra parmesan'],
    cookingTerms: [
      { term: 'Al dente', meaning: 'Tender pasta with a slight bite.' },
      { term: 'Bloom', meaning: 'Warm paste or spices in oil to deepen flavor.' },
    ],
  },
  {
    id: 'recipe-spicy-vodka-rigatoni-budget',
    scanResultId: '001',
    title: 'Budget Spicy Tomato Rigatoni',
    mode: 'Budget',
    description: 'A lower-cost version that keeps the creamy tomato feel with fewer premium ingredients.',
    prepTimeMinutes: 8,
    cookTimeMinutes: 18,
    servings: 2,
    difficulty: 'Easy',
    estimatedHomemadeCost: 4.9,
    estimatedSavings: 33.1,
    ingredients: [
      { name: 'rigatoni', quantity: '8 oz' },
      { name: 'tomato paste', quantity: '2 tbsp' },
      { name: 'milk', quantity: '1/2 cup' },
      { name: 'butter', quantity: '1 tbsp' },
      { name: 'grated parmesan blend', quantity: '1/4 cup' },
      { name: 'red pepper flakes', quantity: '1 tsp', pantryItem: true },
    ],
    steps: [
      'Cook pasta until al dente and reserve pasta water.',
      'Toast tomato paste and red pepper flakes with butter.',
      'Add milk and a splash of pasta water, then simmer until lightly thickened.',
      'Fold in pasta and parmesan blend until creamy.',
    ],
    substitutions: [
      'Use any short pasta already on hand.',
      'Use evaporated milk for a creamier sauce without buying heavy cream.',
    ],
    pantryNote: 'Assumes butter, salt, pepper, and chili flakes may already be on hand.',
    confidenceNote: 'Budget mode is a mock estimate and may trade some restaurant richness for cost savings.',
  },
  {
    id: 'recipe-spicy-vodka-rigatoni-healthy',
    scanResultId: '001',
    title: 'Lighter Spicy Vodka Rigatoni',
    mode: 'Healthy',
    description: 'A lighter take with extra vegetables and Greek yogurt for a creamy finish.',
    prepTimeMinutes: 12,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Medium',
    estimatedHomemadeCost: 7.15,
    estimatedSavings: 30.85,
    ingredients: [
      { name: 'whole wheat rigatoni', quantity: '8 oz' },
      { name: 'tomato paste', quantity: '2 tbsp' },
      { name: 'plain Greek yogurt', quantity: '1/3 cup' },
      { name: 'spinach', quantity: '2 cups' },
      { name: 'parmesan', quantity: '1/4 cup grated' },
      { name: 'red pepper flakes', quantity: '1/2 tsp', pantryItem: true },
    ],
    steps: [
      'Cook whole wheat rigatoni and reserve pasta water.',
      'Bloom tomato paste and red pepper flakes with a small splash of olive oil.',
      'Wilt spinach into the sauce, then remove from heat before stirring in Greek yogurt.',
      'Toss pasta with parmesan and enough pasta water to loosen the sauce.',
    ],
    substitutions: ['Use chickpea pasta for more protein.', 'Swap spinach for kale or arugula.'],
    pantryNote: 'Assumes olive oil, salt, pepper, and red pepper flakes are pantry staples.',
    confidenceNote: 'Healthy mode is a mock estimate and is not a nutrition calculation.',
  },
  {
    id: 'recipe-cheddar-biscuits-restaurant-copy',
    scanResultId: '002',
    title: 'Cheddar-style Biscuits',
    mode: 'Restaurant Copy',
    description: 'Tender cheddar biscuits brushed with garlic butter.',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 6,
    difficulty: 'Easy',
    estimatedHomemadeCost: 2.5,
    estimatedSavings: 9.5,
    ingredients: [
      { name: 'biscuit mix', quantity: '2 cups' },
      { name: 'shredded cheddar', quantity: '1 cup' },
      { name: 'milk', quantity: '2/3 cup' },
      { name: 'butter', quantity: '4 tbsp' },
      { name: 'garlic powder', quantity: '1/2 tsp', pantryItem: true },
    ],
    steps: [
      'Mix biscuit mix, cheddar, and milk until a soft dough forms.',
      'Scoop onto a baking sheet and bake until golden.',
      'Brush with melted garlic butter before serving.',
    ],
    substitutions: ['Use any sharp shredded cheese.', 'Use dairy-free butter if needed.'],
    pantryNote: 'Assumes garlic powder, salt, and pepper are pantry staples.',
    confidenceNote: 'Mock recipe inspired by seafood-chain cheddar biscuits; values are estimates.',
  },
  {
    id: 'recipe-cava-grain-bowl-healthy',
    scanResultId: '003',
    title: 'Cava-style Grain Bowl',
    mode: 'Healthy',
    description: 'A fresh grain bowl with greens, protein, hummus, and harissa dressing.',
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    estimatedHomemadeCost: 5.8,
    estimatedSavings: 11.2,
    ingredients: [
      { name: 'cooked grains', quantity: '2 cups' },
      { name: 'chicken or falafel', quantity: '8 oz' },
      { name: 'cucumber', quantity: '1 cup chopped' },
      { name: 'hummus', quantity: '1/2 cup' },
      { name: 'harissa dressing', quantity: '1/4 cup' },
      { name: 'greens', quantity: '2 cups' },
    ],
    steps: [
      'Layer grains and greens in bowls.',
      'Add protein, cucumber, hummus, and dressing.',
      'Finish with herbs or extra sauce to taste.',
    ],
    substitutions: ['Use rice, lentils, or quinoa as the grain base.', 'Swap chicken for falafel.'],
    pantryNote: 'Assumes salt, pepper, and olive oil are available.',
    confidenceNote: 'Mock bowl composition based on the seed result; nutrition and costs are estimates.',
  },
];

export const mockGroceryLists: GroceryList[] = [
  {
    id: 'grocery-spicy-vodka-rigatoni',
    recipeId: 'recipe-spicy-vodka-rigatoni',
    title: 'Spicy Vodka Rigatoni Grocery List',
    items: [
      { category: 'Noodles / Grains', name: 'rigatoni', quantity: '8 oz', sourceIngredient: '8 oz rigatoni' },
      { category: 'Pantry', name: 'tomato paste', quantity: '1 small can or tube', sourceIngredient: '3 tbsp tomato paste' },
      { category: 'Dairy', name: 'heavy cream', quantity: '1 small carton', sourceIngredient: '1/2 cup heavy cream' },
      { category: 'Dairy', name: 'parmesan', quantity: '1 small wedge or tub', sourceIngredient: '1/3 cup grated parmesan' },
      { category: 'Spices', name: 'red pepper flakes', quantity: 'pantry check', pantryItem: true, pantryStaple: true, sourceIngredient: '1 tsp red pepper flakes' },
      { category: 'Pantry', name: 'olive oil', quantity: '1 tbsp', pantryItem: true, pantryStaple: true, sourceIngredient: '2 tbsp olive oil' },
    ],
  },
  {
    id: 'grocery-cheddar-biscuits',
    recipeId: 'recipe-cheddar-biscuits',
    title: 'Cheddar-style Biscuits Grocery List',
    items: [
      { category: 'Pantry', name: 'biscuit mix', quantity: '1 box', sourceIngredient: '2 cups biscuit mix' },
      { category: 'Dairy', name: 'shredded cheddar', quantity: '1 small bag', sourceIngredient: '1 cup shredded cheddar' },
      { category: 'Dairy', name: 'milk', quantity: '1 small carton if needed', sourceIngredient: '2/3 cup milk' },
      { category: 'Dairy', name: 'butter', quantity: '1 stick', sourceIngredient: '4 tbsp butter' },
      { category: 'Spices', name: 'garlic powder', quantity: 'pantry check', pantryItem: true, pantryStaple: true, sourceIngredient: '1/2 tsp garlic powder' },
    ],
  },
  {
    id: 'grocery-cava-grain-bowl',
    recipeId: 'recipe-cava-grain-bowl',
    title: 'Cava-style Grain Bowl Grocery List',
    items: [
      { category: 'Noodles / Grains', name: 'rice, quinoa, or grains', quantity: '1 pouch or 1 cup dry', sourceIngredient: '2 cups cooked grains' },
      { category: 'Protein', name: 'chicken or falafel', quantity: '8 oz', sourceIngredient: '8 oz chicken or falafel' },
      { category: 'Produce', name: 'cucumber', quantity: '1', sourceIngredient: '1 cup chopped cucumber' },
      { category: 'Sauces / Condiments', name: 'hummus', quantity: '1 small tub', sourceIngredient: '1/2 cup hummus' },
      { category: 'Sauces / Condiments', name: 'harissa dressing', quantity: '1 small bottle', sourceIngredient: '1/4 cup harissa dressing' },
      { category: 'Produce', name: 'greens', quantity: '1 small bag', sourceIngredient: '2 cups greens' },
    ],
  },
];

export const mockShareCards: ShareCard[] = [
  {
    id: 'share-spicy-vodka-rigatoni',
    scanResultId: '001',
    kind: 'scan-result',
    headline: '$38 restaurant pasta -> $6.40 homemade dupe',
    subheadline: 'Saved ~$31.60',
    savedAmount: 31.6,
    matchScore: 8.4,
    footer: 'Made with Okyo',
  },
  {
    id: 'share-cheddar-biscuits',
    scanResultId: '002',
    kind: 'scan-result',
    headline: '$12 cheddar-style biscuits -> $2.50 homemade dupe',
    subheadline: 'Saved ~$9.50',
    savedAmount: 9.5,
    matchScore: 9.1,
    footer: 'Made with Okyo',
  },
  {
    id: 'share-cava-grain-bowl',
    scanResultId: '003',
    kind: 'scan-result',
    headline: '$17 Cava-style bowl -> $5.80 homemade dupe',
    subheadline: 'Saved ~$11.20',
    savedAmount: 11.2,
    matchScore: 8.2,
    footer: 'Made with Okyo',
  },
];

export const mockRestaurantPacks: RestaurantPack[] = [
  {
    id: 'red-lobster-inspired',
    name: 'Red Lobster-inspired',
    dishes: [
      { id: 'red-lobster-cheddar-biscuits', dishName: 'Cheddar-style biscuits', restaurantPrice: 12, homemadeCost: 2.5, estimatedSavings: 9.5, difficulty: 'Easy' },
      { id: 'red-lobster-shrimp-alfredo', dishName: 'Shrimp alfredo', restaurantPrice: 24, homemadeCost: 7.25, estimatedSavings: 16.75, difficulty: 'Medium' },
      { id: 'red-lobster-coconut-shrimp', dishName: 'Coconut shrimp', restaurantPrice: 18, homemadeCost: 7.2, estimatedSavings: 10.8, difficulty: 'Medium' },
    ],
  },
  {
    id: 'starbucks-inspired',
    name: 'Starbucks-inspired',
    dishes: [
      { id: 'starbucks-pink-drink', dishName: 'Pink drink style beverage', restaurantPrice: 7, homemadeCost: 1.8, estimatedSavings: 5.2, difficulty: 'Easy' },
      { id: 'starbucks-cold-brew', dishName: 'Vanilla sweet cream cold brew', restaurantPrice: 6.75, homemadeCost: 1.6, estimatedSavings: 5.15, difficulty: 'Easy' },
      { id: 'starbucks-egg-bites', dishName: 'Egg bites', restaurantPrice: 6.25, homemadeCost: 2.15, estimatedSavings: 4.1, difficulty: 'Medium' },
    ],
  },
  {
    id: 'cava-inspired',
    name: 'Cava-inspired',
    dishes: [
      { id: 'cava-harissa-chicken-bowl', dishName: 'Harissa chicken bowl', restaurantPrice: 17, homemadeCost: 5.9, estimatedSavings: 11.1, difficulty: 'Easy' },
      { id: 'cava-greek-chicken-pita', dishName: 'Greek chicken pita', restaurantPrice: 14, homemadeCost: 4.85, estimatedSavings: 9.15, difficulty: 'Easy' },
    ],
  },
  {
    id: 'sweetgreen-inspired',
    name: 'Sweetgreen-inspired',
    dishes: [
      { id: 'sweetgreen-harvest-bowl', dishName: 'Harvest bowl', restaurantPrice: 18, homemadeCost: 6.2, estimatedSavings: 11.8, difficulty: 'Easy' },
      { id: 'sweetgreen-kale-caesar', dishName: 'Kale caesar with chicken', restaurantPrice: 19, homemadeCost: 6.25, estimatedSavings: 12.75, difficulty: 'Easy' },
    ],
  },
  {
    id: 'cheesecake-factory-inspired',
    name: 'Cheesecake Factory-inspired',
    dishes: [
      { id: 'cheesecake-factory-spicy-vodka-pasta', dishName: 'Spicy vodka-style pasta', restaurantPrice: 38, homemadeCost: 6.4, estimatedSavings: 31.6, difficulty: 'Easy' },
      { id: 'cheesecake-factory-avocado-egg-rolls', dishName: 'Avocado egg rolls', restaurantPrice: 17, homemadeCost: 5.75, estimatedSavings: 11.25, difficulty: 'Medium' },
    ],
  },
  {
    id: 'chipotle-inspired',
    name: 'Chipotle-inspired',
    dishes: [
      { id: 'chipotle-chicken-burrito-bowl', dishName: 'Chicken burrito bowl', restaurantPrice: 14, homemadeCost: 4.8, estimatedSavings: 9.2, difficulty: 'Easy' },
      { id: 'chipotle-guacamole', dishName: 'Guacamole', restaurantPrice: 4, homemadeCost: 1.4, estimatedSavings: 2.6, difficulty: 'Easy' },
    ],
  },
  {
    id: 'erewhon-inspired',
    name: 'Erewhon-inspired',
    dishes: [
      { id: 'erewhon-celebrity-smoothie', dishName: 'Celebrity-style smoothie', restaurantPrice: 19, homemadeCost: 5.5, estimatedSavings: 13.5, difficulty: 'Easy' },
      { id: 'erewhon-wellness-bowl', dishName: 'Wellness bowl', restaurantPrice: 24, homemadeCost: 8.9, estimatedSavings: 15.1, difficulty: 'Easy' },
    ],
  },
];

export const mockXpEvents: XpEventDefinition[] = [
  { id: 'first-scan', label: 'First scan', points: 10 },
  { id: 'save-recipe', label: 'Save recipe', points: 5 },
  { id: 'export-grocery-list', label: 'Export grocery list', points: 10 },
  { id: 'start-dupe-challenge', label: 'Start Dupe Challenge', points: 15 },
  { id: 'complete-dupe-challenge', label: 'Complete Dupe Challenge', points: 40 },
  { id: 'share-card', label: 'Share card', points: 20 },
];

export const mockBadges: Badge[] = [
  { id: 'first-dupe', name: 'First Dupe', description: 'Complete your first restaurant dupe.', unlocked: true },
  { id: 'nailed-it', name: 'Nailed It', description: 'Earn a 9+/10 match score.', unlocked: true },
  { id: 'budget-beast', name: 'Budget Beast', description: 'Save $25+ on one dupe.', unlocked: true },
  { id: 'pasta-hacker', name: 'Pasta Hacker', description: 'Make a pasta dupe at home.', unlocked: true },
  { id: 'healthy-swap-pro', name: 'Healthy Swap Pro', description: 'Complete a Healthy mode dupe.', unlocked: false },
  { id: 'grocery-exporter', name: 'Grocery Exporter', description: 'Export a grocery list.', unlocked: false },
  { id: '100-saved-club', name: '$100 Saved Club', description: 'Reach $100 in estimated savings.', unlocked: false },
];

export const mockLeaderboardEntries: LeaderboardEntry[] = [
  { id: 'leader-biggest-saver-1', rank: 1, displayName: 'Maya', category: 'Biggest Saver This Week', value: '$92 saved', xp: 420 },
  { id: 'leader-biggest-saver-2', rank: 2, displayName: 'Jordan', category: 'Best Match Score', value: '9.4/10 match', xp: 390 },
  { id: 'leader-biggest-saver-3', rank: 3, displayName: 'You', category: 'Biggest Saver This Week', value: '$74 saved', xp: 350 },
  { id: 'leader-most-dupes-4', rank: 4, displayName: 'Sam', category: 'Most Dupes Completed', value: '6 dupes', xp: 310 },
  { id: 'leader-rising-cook-5', rank: 5, displayName: 'Avery', category: 'Rising Cook', value: '+120 XP', xp: 295 },
];
