/* eslint-disable */
// Generated by scripts/generate-oss-notices.mjs — do not edit by hand.
export type OpenSourcePackage = { name: string; version: string; license: string; copyright: string | null };

export const openSourceGeneratedAt = 'checked in from scripts/generate-oss-notices.mjs';
export const openSourceTotalPackageCount = 654;

export const openSourcePackages: OpenSourcePackage[] = [
  {
    "name": "@expo-google-fonts/baloo-2",
    "version": "0.4.2",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo-google-fonts/barlow-condensed",
    "version": "0.4.1",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo-google-fonts/inter",
    "version": "0.4.2",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo-google-fonts/nunito",
    "version": "0.4.2",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo-google-fonts/sora",
    "version": "0.4.2",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@react-native-async-storage/async-storage",
    "version": "2.2.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present, Facebook, Inc."
  },
  {
    "name": "@react-navigation/bottom-tabs",
    "version": "7.16.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 React Navigation Contributors"
  },
  {
    "name": "@react-navigation/native",
    "version": "7.2.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 React Navigation Contributors"
  },
  {
    "name": "@react-navigation/native-stack",
    "version": "7.15.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 React Navigation Contributors"
  },
  {
    "name": "@shopify/react-native-skia",
    "version": "2.4.18",
    "license": "MIT",
    "copyright": "Copyright 2021-present, Shopify Inc."
  },
  {
    "name": "@types/react",
    "version": "19.2.15",
    "license": "MIT",
    "copyright": "Copyright (c) Microsoft Corporation."
  },
  {
    "name": "expo",
    "version": "55.0.28",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-blur",
    "version": "55.0.16",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-clipboard",
    "version": "55.0.15",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-dev-client",
    "version": "55.0.37",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-file-system",
    "version": "55.0.24",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-font",
    "version": "55.0.8",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-haptics",
    "version": "55.0.16",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-image",
    "version": "55.0.11",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-image-manipulator",
    "version": "55.0.19",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-image-picker",
    "version": "55.0.22",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-keep-awake",
    "version": "55.0.8",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-notifications",
    "version": "55.0.25",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-sharing",
    "version": "55.0.22",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-splash-screen",
    "version": "55.0.23",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-status-bar",
    "version": "55.0.6",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "expo-video",
    "version": "55.0.19",
    "license": "MIT",
    "copyright": null
  },
  {
    "name": "iconoir-react-native",
    "version": "7.11.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2021 Daniel Martin, Pascal Jufer"
  },
  {
    "name": "react",
    "version": "19.2.0",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-native",
    "version": "0.83.6",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-native-gesture-handler",
    "version": "2.30.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2016 Software Mansion <swmansion.com>"
  },
  {
    "name": "react-native-pager-view",
    "version": "8.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2021 Callstack"
  },
  {
    "name": "react-native-purchases",
    "version": "10.6.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2023 RevenueCat"
  },
  {
    "name": "react-native-purchases-ui",
    "version": "10.6.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2023 RevenueCat"
  },
  {
    "name": "react-native-reanimated",
    "version": "4.2.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2016 Software Mansion <swmansion.com>"
  },
  {
    "name": "react-native-safe-area-context",
    "version": "5.6.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2019 Th3rd Wave"
  },
  {
    "name": "react-native-screens",
    "version": "4.23.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2018 Software Mansion <swmansion.com>"
  },
  {
    "name": "react-native-svg",
    "version": "15.15.3",
    "license": "MIT",
    "copyright": "Copyright (c) [2015-2016] [Horcrux]"
  },
  {
    "name": "react-native-view-shot",
    "version": "4.0.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2016 Gaëtan Renaudeau"
  },
  {
    "name": "react-native-worklets",
    "version": "0.7.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2024 nobody"
  },
  {
    "name": "tsx",
    "version": "4.23.1",
    "license": "MIT",
    "copyright": "Copyright (c) Hiroki Osame <hiroki.osame@gmail.com>"
  },
  {
    "name": "typescript",
    "version": "5.9.3",
    "license": "Apache-2.0",
    "copyright": "\"Licensor\" shall mean the copyright owner or entity authorized by the copyright owner that is granting the License."
  },
  {
    "name": "zustand",
    "version": "5.0.13",
    "license": "MIT",
    "copyright": "Copyright (c) 2019 Paul Henschel"
  }
];
